import 'package:adventofcode2024/solutions/day24_solution.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences_platform_interface/shared_preferences_async_platform_interface.dart';
import 'package:shared_preferences_platform_interface/in_memory_shared_preferences_async.dart';

void main() {
  SharedPreferencesAsyncPlatform.instance =
      InMemorySharedPreferencesAsync.empty();

  test('Parsing', () {
    Day24Solution s = Day24Solution();
    s.parse(smallExample);
    expect(s.node["x00"], 1);
    expect(s.node["y00"], 0);
    expect(s.node["z01"], -1);
    expect(s.outputNodeNames, ['z00', 'z01', 'z02']);
    expect(s.nodeMap["x01"]!.level, 1);
  });

  test('Get Output', () {
    Day24Solution s = Day24Solution();
    s.parse(smallExample);
    expect(s.getOutput(), 0);
    s.node['z00'] = 1;
    s.node['z01'] = 1;
    s.node['z02'] = 1;
    expect(s.getOutput(), 7);
    s.node['z00'] = 0;
    expect(s.getOutput(), 6);
    s.node['z01'] = 0;
    expect(s.getOutput(), 4);
  });
  test('Part 1 Small', () {
    Day24Solution s = Day24Solution();
    s.parse(smallExample);
    s.part1();
    expect(s.answer1, '4');
  });
  test('Part 1 Big', () {
    Day24Solution s = Day24Solution();
    s.parse(bigExample);
    s.part1();
    expect(s.answer1, '2024');
  });

  test('Part 2 Small', () {
    Day24Solution s = Day24Solution();
    s.parse(smallExample);
    s.part2();
    expect(s.answer2, 'ran 2');
  });

  test('Part 2 MyData', () {
    Day24Solution s = Day24Solution();
    s.parse(myData);
    s.part2();
    expect(s.answer2, 'ran 2');
  });
}

String smallExample = "x00: 1\n"
    "x01: 1\n"
    "x02: 1\n"
    "y00: 0\n"
    "y01: 1\n"
    "y02: 0\n"
    "\n"
    "x00 AND y00 -> z00\n"
    "x01 XOR y01 -> z01\n"
    "x02 OR y02 -> z02\n";

String bigExample = "x00: 1\n"
    "x01: 0\n"
    "x02: 1\n"
    "x03: 1\n"
    "x04: 0\n"
    "y00: 1\n"
    "y01: 1\n"
    "y02: 1\n"
    "y03: 1\n"
    "y04: 1\n"
    "\n"
    "ntg XOR fgs -> mjb\n"
    "y02 OR x01 -> tnw\n"
    "kwq OR kpj -> z05\n"
    "x00 OR x03 -> fst\n"
    "tgd XOR rvg -> z01\n"
    "vdt OR tnw -> bfw\n"
    "bfw AND frj -> z10\n"
    "ffh OR nrd -> bqk\n"
    "y00 AND y03 -> djm\n"
    "y03 OR y00 -> psh\n"
    "bqk OR frj -> z08\n"
    "tnw OR fst -> frj\n"
    "gnj AND tgd -> z11\n"
    "bfw XOR mjb -> z00\n"
    "x03 OR x00 -> vdt\n"
    "gnj AND wpb -> z02\n"
    "x04 AND y00 -> kjc\n"
    "djm OR pbm -> qhw\n"
    "nrd AND vdt -> hwm\n"
    "kjc AND fst -> rvg\n"
    "y04 OR y02 -> fgs\n"
    "y01 AND x02 -> pbm\n"
    "ntg OR kjc -> kwq\n"
    "psh XOR fgs -> tgd\n"
    "qhw XOR tgd -> z09\n"
    "pbm OR djm -> kpj\n"
    "x03 XOR y03 -> ffh\n"
    "x00 XOR y04 -> ntg\n"
    "bfw OR bqk -> z06\n"
    "nrd XOR fgs -> wpb\n"
    "frj XOR qhw -> z04\n"
    "bqk OR frj -> z07\n"
    "y03 OR x01 -> nrd\n"
    "hwm AND bqk -> z03\n"
    "tgd XOR rvg -> z12\n"
    "tnw OR pbm -> gnj\n";

String myData = "x00: 1\n"
    "x01: 1\n"
    "x02: 0\n"
    "x03: 0\n"
    "x04: 0\n"
    "x05: 1\n"
    "x06: 0\n"
    "x07: 1\n"
    "x08: 1\n"
    "x09: 0\n"
    "x10: 1\n"
    "x11: 0\n"
    "x12: 0\n"
    "x13: 0\n"
    "x14: 1\n"
    "x15: 1\n"
    "x16: 1\n"
    "x17: 0\n"
    "x18: 0\n"
    "x19: 0\n"
    "x20: 1\n"
    "x21: 0\n"
    "x22: 1\n"
    "x23: 0\n"
    "x24: 0\n"
    "x25: 0\n"
    "x26: 0\n"
    "x27: 1\n"
    "x28: 0\n"
    "x29: 1\n"
    "x30: 0\n"
    "x31: 0\n"
    "x32: 1\n"
    "x33: 1\n"
    "x34: 1\n"
    "x35: 0\n"
    "x36: 0\n"
    "x37: 0\n"
    "x38: 1\n"
    "x39: 1\n"
    "x40: 1\n"
    "x41: 1\n"
    "x42: 0\n"
    "x43: 0\n"
    "x44: 1\n"
    "y00: 1\n"
    "y01: 0\n"
    "y02: 1\n"
    "y03: 1\n"
    "y04: 0\n"
    "y05: 0\n"
    "y06: 1\n"
    "y07: 1\n"
    "y08: 0\n"
    "y09: 1\n"
    "y10: 1\n"
    "y11: 1\n"
    "y12: 1\n"
    "y13: 0\n"
    "y14: 1\n"
    "y15: 0\n"
    "y16: 0\n"
    "y17: 1\n"
    "y18: 0\n"
    "y19: 1\n"
    "y20: 0\n"
    "y21: 1\n"
    "y22: 1\n"
    "y23: 1\n"
    "y24: 0\n"
    "y25: 1\n"
    "y26: 1\n"
    "y27: 0\n"
    "y28: 1\n"
    "y29: 1\n"
    "y30: 0\n"
    "y31: 1\n"
    "y32: 0\n"
    "y33: 0\n"
    "y34: 0\n"
    "y35: 1\n"
    "y36: 1\n"
    "y37: 1\n"
    "y38: 1\n"
    "y39: 1\n"
    "y40: 0\n"
    "y41: 1\n"
    "y42: 0\n"
    "y43: 1\n"
    "y44: 1\n"
    "\n"
    "x23 AND y23 -> mhq\n"
    "dbf XOR dsb -> z35\n"
    "x41 AND y41 -> qss\n"
    "kbv AND ctw -> qhg\n"
    "djs OR tgk -> ccp\n"
    "nmw AND bgp -> bcr\n"
    "jns OR npn -> jbv\n"
    "y29 AND x29 -> tjt\n"
    "y17 AND x17 -> nhh\n"
    "kmm AND ptk -> vnr\n"
    "hbr AND qfp -> mjr\n"
    "qfk AND pvj -> ndp\n"
    "tvb XOR jhd -> z25\n"
    "y29 XOR x29 -> wft\n"
    "rqd AND cns -> grb\n"
    "jbv AND kjg -> vjg\n"
    "tvm XOR pkw -> z38\n"
    "vwd AND kvv -> mgw\n"
    "nmw XOR bgp -> z02\n"
    "cdc OR stq -> z21\n"
    "x16 XOR y16 -> mft\n"
    "x37 XOR y37 -> hbr\n"
    "x24 XOR y24 -> cns\n"
    "y40 XOR x40 -> pgc\n"
    "ccd OR cst -> cbk\n"
    "fht XOR ddw -> z20\n"
    "wft AND nnq -> stm\n"
    "srk AND sjm -> fwg\n"
    "y06 AND x06 -> cnm\n"
    "gqg XOR pmv -> z07\n"
    "ndp OR nfq -> rgv\n"
    "bsm OR vsc -> fjn\n"
    "x15 XOR y15 -> srk\n"
    "bwv XOR vbq -> z42\n"
    "kbv XOR ctw -> z31\n"
    "x10 XOR y10 -> htc\n"
    "x08 XOR y08 -> knh\n"
    "fgc AND dvm -> nfn\n"
    "y03 AND x03 -> ssj\n"
    "x26 XOR y26 -> spf\n"
    "y02 AND x02 -> psw\n"
    "x36 XOR y36 -> fcf\n"
    "ptj OR dtg -> spg\n"
    "stm OR tjt -> gsj\n"
    "mmw XOR ncf -> z23\n"
    "y26 AND x26 -> csh\n"
    "rrj AND mft -> tnt\n"
    "x05 XOR y05 -> chs\n"
    "x16 AND y16 -> khn\n"
    "nqm AND fmf -> tgq\n"
    "wft XOR nnq -> z29\n"
    "y13 AND x13 -> ggg\n"
    "rcb OR khg -> mfp\n"
    "y28 AND x28 -> wgd\n"
    "csf AND bck -> qsg\n"
    "x31 XOR y31 -> kbv\n"
    "rrj XOR mft -> z16\n"
    "hhg AND ccp -> msp\n"
    "y00 XOR x00 -> z00\n"
    "x25 XOR y25 -> khg\n"
    "x42 AND y42 -> djs\n"
    "ggg OR hvg -> csf\n"
    "pps XOR wdg -> vdc\n"
    "y04 XOR x04 -> pvj\n"
    "qtg AND knh -> ccd\n"
    "x27 AND y27 -> jns\n"
    "jdk OR pmr -> spk\n"
    "nhm XOR jmr -> z18\n"
    "fpk AND dfh -> ccr\n"
    "x06 XOR y06 -> bgq\n"
    "x38 AND y38 -> dcc\n"
    "x22 XOR y22 -> jkq\n"
    "vbq AND bwv -> tgk\n"
    "x14 XOR y14 -> bck\n"
    "fjn AND htc -> dtg\n"
    "kfd XOR rtg -> z19\n"
    "bvk OR khh -> nmw\n"
    "x34 XOR y34 -> ptk\n"
    "mmw AND ncf -> rkf\n"
    "y11 AND x11 -> rvg\n"
    "wgd OR vjg -> nnq\n"
    "qss OR wtt -> bwv\n"
    "dmb OR crv -> ddw\n"
    "y08 AND x08 -> cst\n"
    "nhh OR tgq -> jmr\n"
    "cpt XOR fqc -> z32\n"
    "tnt OR khn -> fmf\n"
    "fbk AND tcq -> hvg\n"
    "spq XOR gpk -> z01\n"
    "x02 XOR y02 -> bgp\n"
    "x20 AND y20 -> fct\n"
    "x36 AND y36 -> jbq\n"
    "x12 AND y12 -> z12\n"
    "mfp XOR spf -> z26\n"
    "spg XOR hhm -> z11\n"
    "y32 AND x32 -> rjq\n"
    "y04 AND x04 -> nfq\n"
    "pkj OR msp -> kvv\n"
    "tvc OR dcc -> dvm\n"
    "vnr OR krb -> dbf\n"
    "fmf XOR nqm -> z17\n"
    "rtg AND kfd -> dmb\n"
    "fvh XOR pgc -> z40\n"
    "fcf XOR spk -> z36\n"
    "pvc OR gst -> kmm\n"
    "cbk AND nbm -> vsc\n"
    "x09 AND y09 -> bsm\n"
    "x07 XOR y07 -> gqg\n"
    "ptk XOR kmm -> z34\n"
    "x28 XOR y28 -> kjg\n"
    "dbm OR jft -> qtg\n"
    "jbr AND wcs -> z33\n"
    "y42 XOR x42 -> vbq\n"
    "y00 AND x00 -> spq\n"
    "y19 XOR x19 -> kfd\n"
    "tbn OR grb -> jhd\n"
    "kvv XOR vwd -> z44\n"
    "wcs XOR jbr -> gst\n"
    "srk XOR sjm -> z15\n"
    "y39 AND x39 -> cbf\n"
    "bgq XOR wdh -> z06\n"
    "bbn AND rsc -> cdc\n"
    "y18 XOR x18 -> nhm\n"
    "tvm AND pkw -> tvc\n"
    "x23 XOR y23 -> ncf\n"
    "x19 AND y19 -> crv\n"
    "qhg OR gnc -> fqc\n"
    "jbv XOR kjg -> z28\n"
    "y05 AND x05 -> nph\n"
    "x32 XOR y32 -> cpt\n"
    "x31 AND y31 -> gnc\n"
    "ccp XOR hhg -> z43\n"
    "x15 AND y15 -> gtf\n"
    "jmr AND nhm -> ptd\n"
    "x10 AND y10 -> ptj\n"
    "bgq AND wdh -> dgh\n"
    "ftw XOR gsj -> z30\n"
    "x44 AND y44 -> bds\n"
    "fjn XOR htc -> z10\n"
    "y43 AND x43 -> pkj\n"
    "y30 AND x30 -> nmj\n"
    "tvb AND jhd -> rcb\n"
    "x40 AND y40 -> gdm\n"
    "mgw OR bds -> z45\n"
    "fdv AND dfs -> wtt\n"
    "rkf OR mhq -> rqd\n"
    "pvj XOR qfk -> z04\n"
    "pmv AND gqg -> dbm\n"
    "x21 XOR y21 -> bbn\n"
    "x38 XOR y38 -> tvm\n"
    "mjr OR kpb -> pkw\n"
    "jbq OR vmj -> qfp\n"
    "jkq XOR nhn -> z22\n"
    "qfn OR fct -> rsc\n"
    "x30 XOR y30 -> ftw\n"
    "y35 XOR x35 -> dsb\n"
    "y24 AND x24 -> tbn\n"
    "fcf AND spk -> vmj\n"
    "cnm OR dgh -> pmv\n"
    "x27 XOR y27 -> mcv\n"
    "chs XOR rgv -> z05\n"
    "vdc OR kcp -> fbk\n"
    "y39 XOR x39 -> fgc\n"
    "x13 XOR y13 -> tcq\n"
    "ssj OR ccr -> qfk\n"
    "fwg OR gtf -> rrj\n"
    "knh XOR qtg -> z08\n"
    "fqc AND cpt -> nfh\n"
    "y17 XOR x17 -> nqm\n"
    "hbr XOR qfp -> z37\n"
    "y22 AND x22 -> nrq\n"
    "y01 XOR x01 -> gpk\n"
    "jhv OR nph -> wdh\n"
    "dfs XOR fdv -> z41\n"
    "gqb OR csh -> mbp\n"
    "dvm XOR fgc -> z39\n"
    "y03 XOR x03 -> fpk\n"
    "mfp AND spf -> gqb\n"
    "x44 XOR y44 -> vwd\n"
    "gpk AND spq -> bvk\n"
    "x21 AND y21 -> stq\n"
    "cbf OR nfn -> fvh\n"
    "spg AND hhm -> wvv\n"
    "cns XOR rqd -> z24\n"
    "rjq OR nfh -> wcs\n"
    "mcv AND mbp -> npn\n"
    "wdg AND pps -> kcp\n"
    "nrq OR vkg -> mmw\n"
    "x33 AND y33 -> pvc\n"
    "x20 XOR y20 -> fht\n"
    "y43 XOR x43 -> hhg\n"
    "dfh XOR fpk -> z03\n"
    "fbk XOR tcq -> z13\n"
    "x09 XOR y09 -> nbm\n"
    "pwp OR nmj -> ctw\n"
    "y25 AND x25 -> tvb\n"
    "y34 AND x34 -> krb\n"
    "x11 XOR y11 -> hhm\n"
    "hdq OR gdm -> fdv\n"
    "mcv XOR mbp -> z27\n"
    "nbm XOR cbk -> z09\n"
    "fvh AND pgc -> hdq\n"
    "jkq AND nhn -> vkg\n"
    "dwt OR qsg -> sjm\n"
    "dbf AND dsb -> pmr\n"
    "rsc XOR bbn -> nhn\n"
    "y14 AND x14 -> dwt\n"
    "x35 AND y35 -> jdk\n"
    "x41 XOR y41 -> dfs\n"
    "y37 AND x37 -> kpb\n"
    "bck XOR csf -> z14\n"
    "y07 AND x07 -> jft\n"
    "sdp OR ptd -> rtg\n"
    "y01 AND x01 -> khh\n"
    "bcr OR psw -> dfh\n"
    "chs AND rgv -> jhv\n"
    "y18 AND x18 -> sdp\n"
    "ddw AND fht -> qfn\n"
    "x33 XOR y33 -> jbr\n"
    "gsj AND ftw -> pwp\n"
    "x12 XOR y12 -> pps\n"
    "rvg OR wvv -> wdg\n";
